@@startuml
 package Modelo.SistemaCartas.Joker.Jokers {

     interface Joker {
         +void activar(Jugador jugador)
     }

     abstract class JokerGenerico implements Joker {
         -String nombre
         -String descripcion
         -int puntaje
         -int multiplicador
         -Efecto efecto

         +JokerGenerico(String nombre, String descripcion, int puntaje, int multiplicador)
         +String getNombre()
         +String getDescripcion()
         +void activar(Jugador jugador)
     }

     class Sumador extends JokerGenerico {
         +Sumador(String nombre, String descripcion, int puntaje, int multiplicador)
     }

     class Multiplicador extends JokerGenerico {
         +Multiplicador(String nombre, String descripcion, int puntaje, int multiplicador)
     }

     class Descarte extends JokerGenerico {
         +Descarte(String nombre, String descripcion, int puntaje, int multiplicador)
     }

     class unoEn extends JokerGenerico{
        +UnoEn(String nombre, String descripcion, int puntaje, int multiplicador, int probabilidad)
     }

     class PorJugada extends JokerGenerico{
        +PorJugada(String nombre, String descripcion, int puntaje, int multiplicador, String jugada)
     }

     class Combinacion implements Joker {
         -String nombre
         -String descripcion
         -ArrayList<Joker> subcomodines

         +Combinacion(String nombre, String descripcion, ArrayList<Joker> subcomodines)
         +void activar(Jugador jugador)
         +String getDescripcion()
     }
 }

 package Modelo.SistemaCartas.Joker.SistemaDeEfecto {
     interface Efecto{
         +void activar(int puntaje, int multiplicador, Jugador jugador)
     }
     class SumaPuntaje extends Efecto {
     +activar(int puntos, int multiplicador, Jugador jugador)
     }
     class MultiplicacionMult extends Efecto {
     +activar(int puntos, int multiplicador, Jugador jugador)
     }
     class ActivacionDescarte extends Efecto {
     +activar(int puntos, int multiplicador, Jugador jugador)
     }
     class ActivacionAleatoria extends Efecto{
     -Int probabilidad
     -Random random
     +activar(int puntos, int multiplicador, Jugador jugador)
     +seActivo()
     }
     class ActivacionJugada extends Efecto{
     +activacionJugada(String jugada)
     +activar(int puntos, int multiplicador, Jugador jugador)
     }

}


Efecto<----JokerGenerico
Combinacion "1" -> "*" JokerGenerico


 @enduml
