@startuml Diagrama de Clases - General

class Jugador{
    - List<Carta> mano_cartas (limit 5) 
    - Puntos

    + descartarCartas()
    + jugarMano() // Debe elegir 5 primero
    - elegirCarta() : return Carta unaCarta
    - cancelarCarta() 
    + comprarCarta(Carta unaCarta)
    
}

{abstract} class Carta{
    - puntaje 
    - efecto 

    + calcularPuntaje()
} 


' Relaciones
Jugador --> Carta : Mano Max 8 
Jugador --> Puntación
Carta --> Puntuación


@enduml