@startuml
package Modelo.SistemaCartas.Activables.Tarot{
    abstract class Tarot implements Activable{
    - nombre:String
    - descripcion:String
    - puntos:int
    - multiplicador:Multiplicador
    - efecto:Efecto
    +Tarot(String nombre, String descripcion, int incrementador, Multiplicador multiplicador, Efecto efecto)
    +{abstract}activar(Mano mano, String contexto)
    }

    class MejoraJugada extends Tarot{
    +MejoraJugada(String nombre, String descripcion, int incrementador, Multiplicador multiplicador, Efecto efecto)
    +activar(Mano mano, String contexto)
    }

  Tarot->Efecto

}


@enduml