@startuml
participant Actor
Actor -> Mano : determinarJugada
activate Mano
loop jugadasPosibles
Mano -> Jugada : esJugadaValida
activate Jugada
Jugada --> Mano
deactivate Jugada
alt jugada.esJugadaValida(cartas)
note right of Mano : Empty
end
note right of Mano : Empty
end
return
@enduml